# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd655811578b83d93b3af4ad171f61ac42d1b14b60758c5f4c027106259892dd6447caacef289821de7960013ffb2588f079a07e8f1244bd89b839b705a001d

test:
  secret_key_base: 44eddf7c04d376c8e8afdc42573f0e52f5222122919e401efbef28bd96a68942b070f7106cc4cea9b36fd147ad7ac5b9e4dabdfa86e350be5ade3fe6697deea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
